Add pagination support in posts list
Karthikeyantestpress/Django_Blog_Application pull request #7
Opened 2022-11-13 08:54 UTC by Karthikeyantestpress

2022-11-24 09:46 UTC, waranlogesh requested changes

2022-11-24 09:46 UTC, waranlogesh commented on mysite/blog/views.py
> +def paginate(Published_posts,page, Total_posts_per_page):
use proper case for variable names

2022-11-24 09:55 UTC, Karthikeyantestpress commented on mysite/blog/views.py
> +def paginate(Published_posts,page, Total_posts_per_page):
Updated  proper case for variable names

2022-12-05 08:52 UTC, waranlogesh approved these changes

2022-12-05 09:08 UTC, merged