Add sharing post by email support to the detail view
Karthikeyantestpress/Django_Blog_Application pull request #9
Opened 2022-11-13 09:11 UTC by Karthikeyantestpress

2022-12-05 08:53 UTC, waranlogesh requested changes

2022-12-05 08:53 UTC, waranlogesh commented on mysite/mysite/settings.py
> +EMAIL_USE_TLS = True
Use django environ

2022-12-05 10:27 UTC, Karthikeyantestpress commented on mysite/mysite/settings.py
> +EMAIL_USE_TLS = True
[https://github.com/Karthikeyantestpress/Django_Blog_Application/pull/9/files#diff-523c7df6908f5a99ed3fd1b044f8460a635ce54ffcef889c1b7cdfe6c438c0af:~:text=env%20%3D%20environ,%22EMAIL_USE_TLS%22)](url)

2022-12-06 09:34 UTC, waranlogesh approved these changes

2022-12-06 09:51 UTC, merged